// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bufbhxptciyogmggmvfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1ZmJoeHB0Y2l5b2dtZ2dtdmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTQ3MzAsImV4cCI6MjA3Mjk5MDczMH0.VB-CdJ5WALNQfyaYXpn8gvBrR2Egcx_duGWUIJ82Rqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});